server:
  port: 81

country: china
province: beijing
city: beijing
area: haidian

user:
  username: wendy
  age: 18

likes:
  - game
  - music
  - sleep

users:
  - name: Tom
    age: 20
  - name: Jim
    age: 23

